import type { Findable, HabitatId } from './types.ts';

const draft = { status: 'draft' as const };

/**
 * Everything a child can tap, in stop order (reef → seagrass → sand). The five
 * featured organisms keep their full cards; the rest are "spotters" with one
 * short fact written for the youngest learners (TK–2) and read aloud.
 */
export const findables: Findable[] = [
  // ── Reef ────────────────────────────────────────────────────────────────
  {
    id: 'elkhorn-coral',
    title: 'Elkhorn coral',
    name: 'elkhorn coral',
    habitat: 'reef',
    featured: true,
    contentVersion: 1,
    review: draft,
    sources: ['noaa-elkhorn'],
    line: 'Elkhorn coral! Its wide branches look like antlers, and little fish hide between them.',
    accessibleDescription: 'Golden-brown coral with wide, flat branches like antlers.',
    assets: ['proc-elkhorn-coral', 'svg-elkhorn-coral'],
  },
  {
    id: 'stoplight-parrotfish',
    title: 'Stoplight parrotfish',
    name: 'parrotfish',
    habitat: 'reef',
    featured: true,
    contentVersion: 1,
    review: draft,
    sources: ['fishbase-stoplight'],
    line: 'A stoplight parrotfish! It scrapes algae off rocks with its beak-like teeth.',
    accessibleDescription: 'A bright green fish with a beak-like mouth, nibbling a rock.',
    assets: ['proc-parrotfish', 'svg-parrotfish'],
  },
  {
    id: 'great-barracuda',
    title: 'Great barracuda',
    name: 'barracuda',
    habitat: 'reef',
    featured: true,
    contentVersion: 1,
    review: draft,
    sources: ['flmnh-barracuda'],
    line: 'A great barracuda! It is a long, fast hunter that eats other fish.',
    accessibleDescription: 'A long, slim, silver fish with dark spots.',
    assets: ['proc-barracuda', 'svg-barracuda'],
  },
  {
    id: 'brain-coral',
    title: 'Brain coral',
    name: 'brain coral',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['naturalis-brain-coral', 'noaa-coral-animal'],
    line: 'Brain coral! Its wiggly grooves look like a brain. It is an animal, and it helps build the reef.',
    accessibleDescription: 'A round, tan coral covered in wiggly grooves.',
    assets: ['proc-brain-coral', 'svg-spotters'],
  },
  {
    id: 'sea-fan',
    title: 'Sea fan',
    name: 'sea fan',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['mote-sea-fan'],
    line: 'A sea fan! It holds its branches out like a net to catch tiny bits of food floating by.',
    accessibleDescription: 'A flat, purple, fan-shaped soft coral that sways in the water.',
    assets: ['proc-environment', 'svg-spotters'],
  },
  {
    id: 'tube-sponge',
    title: 'Tube sponge',
    name: 'sponge',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['noaa-barrel-sponge'],
    line: 'A sponge! Sponges are animals full of tiny holes. Water flows through them and brings them food.',
    accessibleDescription: 'A cluster of orange and purple tubes standing up from the reef.',
    assets: ['proc-environment', 'svg-spotters'],
  },
  {
    id: 'nurse-shark',
    title: 'Nurse shark',
    name: 'nurse shark',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['flmnh-nurse-shark', 'belize-hol-chan'],
    line: 'A nurse shark! It likes to rest on the sea floor during the day and look for food at night.',
    accessibleDescription: 'A tan shark with a rounded head and long tail, resting on the sand.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  {
    id: 'spiny-lobster',
    title: 'Spiny lobster',
    name: 'spiny lobster',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['adw-spiny-lobster'],
    line: 'A spiny lobster! It hides in holes in the reef. It has long, spiny feelers but no big claws.',
    accessibleDescription: 'A reddish-brown lobster with long antennae, peeking out from a rock.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  {
    id: 'sea-urchin',
    title: 'Long-spined sea urchin',
    name: 'sea urchin',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['noaa-diadema'],
    line: 'A sea urchin! It is covered in long, pointy spines, and it eats algae off the reef.',
    accessibleDescription: 'A small, round, black animal covered in long thin spines.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  {
    id: 'green-moray',
    title: 'Green moray eel',
    name: 'moray eel',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['flmnh-green-moray'],
    line: 'A green moray eel! It peeks out of a rocky hole and opens and closes its mouth to breathe.',
    accessibleDescription: 'A green eel poking its head out of a hole in a rock.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  {
    id: 'reef-octopus',
    title: 'Caribbean reef octopus',
    name: 'octopus',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['mote-reef-octopus'],
    line: 'An octopus! It can change its color to match the things around it. Watch!',
    accessibleDescription: 'A blue-green octopus with eight curling arms, sitting on the reef floor.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  {
    id: 'blue-tang',
    title: 'Blue tang',
    name: 'blue tangs',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['flmnh-blue-tang'],
    line: 'Blue tangs! These bright blue fish swim in little groups and nibble algae.',
    accessibleDescription: 'Three bright blue, oval fish swimming together.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  {
    id: 'sergeant-major',
    title: 'Sergeant major',
    name: 'sergeant major fish',
    habitat: 'reef',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['flmnh-sergeant-major'],
    line: 'Sergeant major fish! Their black stripes look like the stripes on a soldier’s uniform.',
    accessibleDescription: 'Small yellow and white fish with black stripes.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  // ── Seagrass meadow ─────────────────────────────────────────────────────
  {
    id: 'green-sea-turtle',
    title: 'Green sea turtle',
    name: 'sea turtle',
    habitat: 'seagrass',
    featured: true,
    contentVersion: 1,
    review: draft,
    sources: ['noaa-green-turtle'],
    line: 'A green sea turtle! Grown-up green turtles munch on seagrass.',
    accessibleDescription: 'A large sea turtle with a brown patterned shell, resting in the seagrass.',
    assets: ['proc-turtle', 'svg-turtle'],
  },
  {
    id: 'eagle-ray',
    title: 'Spotted eagle ray',
    name: 'eagle ray',
    habitat: 'seagrass',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['flmnh-eagle-ray'],
    line: 'A spotted eagle ray! It flaps its big fins like wings, so it looks like it is flying through the water.',
    accessibleDescription: 'A dark, diamond-shaped ray with white spots and a long thin tail, gliding above the seagrass.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  {
    id: 'cushion-star',
    title: 'Cushion sea star',
    name: 'sea star',
    habitat: 'seagrass',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['lamar-cushion-star'],
    line: 'A cushion sea star! It has five short, thick arms and lives on sand and seagrass.',
    accessibleDescription: 'An orange, puffy, five-armed sea star lying among the seagrass.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  {
    id: 'sea-cucumber',
    title: 'Sea cucumber',
    name: 'sea cucumber',
    habitat: 'seagrass',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['knowable-sea-cucumber'],
    line: 'A sea cucumber! It crawls slowly along the sea floor, eating sand and cleaning it as it goes.',
    accessibleDescription: 'A long, soft, brown animal shaped like a cucumber, lying on the sea floor.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  // ── Sandy seabed ────────────────────────────────────────────────────────
  {
    id: 'queen-conch',
    title: 'Queen conch',
    name: 'queen conch',
    habitat: 'sand',
    featured: true,
    contentVersion: 1,
    review: draft,
    sources: ['noaa-queen-conch'],
    line: 'A queen conch! It is a big sea snail with a pink shell inside, and it eats algae.',
    accessibleDescription: 'A large spiral shell with a pink lip, partly covered in algae.',
    assets: ['proc-conch', 'svg-conch'],
  },
  {
    id: 'southern-stingray',
    title: 'Southern stingray',
    name: 'stingray',
    habitat: 'sand',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['flmnh-southern-stingray', 'belize-hol-chan'],
    line: 'A southern stingray! It can hide under the sand with just its eyes peeking out.',
    accessibleDescription: 'A flat, diamond-shaped grey ray lying on the sand, partly covered.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
  {
    id: 'hermit-crab',
    title: 'Hermit crab',
    name: 'hermit crab',
    habitat: 'sand',
    featured: false,
    contentVersion: 1,
    review: draft,
    sources: ['britannica-hermit-crab'],
    line: 'A hermit crab! It lives in an empty shell and moves into a bigger one as it grows.',
    accessibleDescription: 'A small red crab peeking out of a spiral shell on the sand.',
    assets: ['proc-spotters', 'svg-spotters'],
  },
];

export const findableById = new Map(findables.map((f) => [f.id, f]));
export const spotters = findables.filter((f) => !f.featured);
export const findablesAt = (stop: HabitatId) => findables.filter((f) => f.habitat === stop);

/** Narration ids for the read-aloud fact and the game prompt. */
export const spotterNarrationId = (id: string) => `spotter-${id}`;
export const findNarrationId = (id: string) => `find-${id}`;

export const FIND_LINES = {
  intro: 'Let’s play Can You Find! Listen for an ocean animal. Then come up and tap it.',
  yes: 'You found it!',
  done: 'You found every animal! Amazing exploring!',
  remember: 'Remember, in the real ocean we look at animals, but we never touch them.',
};
