import type { Source } from './types.ts';

/**
 * Source register. Each entry says what the source supports — and its limits.
 * Sources support the educational direction; they do not replace species-level
 * review by a qualified reviewer before publication.
 */
export const sources: Source[] = [
  {
    id: 'bz-hcmr',
    title: 'Hol Chan Marine Reserve',
    publisher: 'Belize Fisheries Department',
    url: 'https://fisheries.gov.bz/hcmr/',
    supports:
      'Linked reef, seagrass and mangrove habitats in Belize and local ecology education. Supports the Belize habitat context — not an exact reconstruction of the reserve.',
    accessed: '2026-10-05',
  },
  {
    id: 'noaa-reef-ecosystems',
    title: 'Coral reef ecosystems',
    publisher: 'NOAA Education',
    url: 'https://www.noaa.gov/education/resource-collections/marine-life/coral-reef-ecosystems',
    supports: 'Reefs provide habitat functions including food and shelter. Supports the lesson’s central relationship.',
    accessed: '2026-10-05',
  },
  {
    id: 'noaa-coral-animal',
    title: 'Are corals animals or plants?',
    publisher: 'NOAA National Ocean Service',
    url: 'https://oceanservice.noaa.gov/facts/coral.html',
    supports: 'Coral is an animal; reef-building corals form the reef structure.',
    accessed: '2026-10-05',
  },
  {
    id: 'noaa-marine-life',
    title: 'Marine life',
    publisher: 'NOAA Education',
    url: 'https://www.noaa.gov/education/resource-collections/marine-life',
    supports: 'Educational starting point for marine food relationships. Specific food-web edges are sourced separately.',
    accessed: '2026-10-05',
  },
  {
    id: 'noaa-elkhorn',
    title: 'Elkhorn coral (Acropora palmata)',
    publisher: 'NOAA Fisheries',
    url: 'https://www.fisheries.noaa.gov/species/elkhorn-coral',
    supports:
      'Caribbean reef-building coral; forms thickets in very shallow water that provide habitat for reef animals, especially fish; gets most of its energy from symbiotic zooxanthellae.',
    accessed: '2026-10-06',
  },
  {
    id: 'noaa-green-turtle',
    title: 'Green turtle (Chelonia mydas)',
    publisher: 'NOAA Fisheries',
    url: 'https://www.fisheries.noaa.gov/species/green-turtle',
    supports:
      'Adult green turtles are mainly herbivores that eat seagrasses and algae; juveniles are more omnivorous. Supports the life-stage qualifier on the seagrass → turtle link.',
    accessed: '2026-10-06',
  },
  {
    id: 'noaa-queen-conch',
    title: 'Queen conch (Aliger gigas)',
    publisher: 'NOAA Fisheries',
    url: 'https://www.fisheries.noaa.gov/species/queen-conch',
    supports:
      'Queen conch are grazing herbivores that eat algae and seagrass detritus; juveniles are associated with seagrass beds, adults with sandy algal flats.',
    accessed: '2026-10-06',
  },
  {
    id: 'fishbase-stoplight',
    title: 'Sparisoma viride, Stoplight parrotfish',
    publisher: 'FishBase',
    url: 'https://fishbase.se/summary/1161',
    supports:
      'Stoplight parrotfish feed mainly on algae, scraping it from dead coral and rock surfaces. Diet is species-specific — not all parrotfish eat the same things.',
    accessed: '2026-10-06',
  },
  {
    id: 'flmnh-barracuda',
    title: 'Great barracuda (Sphyraena barracuda)',
    publisher: 'Florida Museum of Natural History',
    url: 'https://www.floridamuseum.ufl.edu/discover-fish/species-profiles/great-barracuda',
    supports: 'Great barracuda are reef predators that eat mostly fish, plus some squid and shrimp, and hunt by sight.',
    accessed: '2026-10-06',
  },
  {
    id: 'belize-hol-chan',
    title: 'Hol Chan Marine Reserve and Shark Ray Alley',
    publisher: 'Belize.com',
    url: 'https://belize.com/hol-chan/',
    supports: 'Shark Ray Alley in Hol Chan is a shallow sandy area known for nurse sharks and southern stingrays. Belize context only.',
    accessed: '2026-10-07',
  },
  {
    id: 'flmnh-nurse-shark',
    title: 'Nurse shark (Ginglymostoma cirratum)',
    publisher: 'Florida Museum of Natural History',
    url: 'https://www.floridamuseum.ufl.edu/discover-fish/species-profiles/nurse-shark/',
    supports: 'Nurse sharks rest on sandy bottoms or in caves and crevices by day and hunt at night.',
    accessed: '2026-10-07',
  },
  {
    id: 'flmnh-southern-stingray',
    title: 'Southern stingray (Hypanus americanus)',
    publisher: 'Florida Museum of Natural History',
    url: 'https://www.floridamuseum.ufl.edu/discover-fish/species-profiles/southern-stingray/',
    supports: 'Southern stingrays bury themselves in sand, often with only their eyes showing.',
    accessed: '2026-10-07',
  },
  {
    id: 'flmnh-eagle-ray',
    title: 'Spotted eagle ray (Aetobatus narinari)',
    publisher: 'Florida Museum of Natural History',
    url: 'https://www.floridamuseum.ufl.edu/discover-fish/species-profiles/aetobatus-narinari/',
    supports: 'Spotted eagle rays swim with wing-like pectoral fins over bays, reefs and sand.',
    accessed: '2026-10-07',
  },
  {
    id: 'adw-spiny-lobster',
    title: 'Panulirus argus (Caribbean spiny lobster)',
    publisher: 'Animal Diversity Web, University of Michigan',
    url: 'https://animaldiversity.org/accounts/Panulirus_argus/',
    supports: 'Caribbean spiny lobsters hide in reef crevices by day, have long spiny antennae and no large claws.',
    accessed: '2026-10-07',
  },
  {
    id: 'noaa-diadema',
    title: 'Long-spined sea urchins',
    publisher: 'NOAA National Ocean Service',
    url: 'https://oceanservice.noaa.gov/podcast/july22/nop57-long-spined-sea-urchins.html',
    supports: 'Long-spined sea urchins are important algae grazers on Caribbean reefs.',
    accessed: '2026-10-07',
  },
  {
    id: 'flmnh-green-moray',
    title: 'Green moray (Gymnothorax funebris)',
    publisher: 'Florida Museum of Natural History',
    url: 'https://www.floridamuseum.ufl.edu/discover-fish/species-profiles/gymnothorax-funebris/',
    supports: 'Green morays hide in rocky crevices by day with the head out, and open and close the mouth to breathe.',
    accessed: '2026-10-07',
  },
  {
    id: 'mote-reef-octopus',
    title: 'Caribbean reef octopus',
    publisher: 'Mote Marine Laboratory',
    url: 'https://mote.org/animal-encyclopedia/caribbean-reef-octopus/',
    supports: 'The Caribbean reef octopus lives on reefs and seagrass and changes color to blend in.',
    accessed: '2026-10-07',
  },
  {
    id: 'flmnh-blue-tang',
    title: 'Blue tang (Acanthurus coeruleus)',
    publisher: 'Florida Museum of Natural History',
    url: 'https://www.floridamuseum.ufl.edu/discover-fish/species-profiles/blue-tang/',
    supports: 'Blue tangs graze algae and often swim in small groups.',
    accessed: '2026-10-07',
  },
  {
    id: 'flmnh-sergeant-major',
    title: 'Sergeant major (Abudefduf saxatilis)',
    publisher: 'Florida Museum of Natural History',
    url: 'https://www.floridamuseum.ufl.edu/discover-fish/species-profiles/sergeant-major/',
    supports: 'Sergeant majors are named for black stripes like a military rank insignia.',
    accessed: '2026-10-07',
  },
  {
    id: 'lamar-cushion-star',
    title: 'Cushion star',
    publisher: 'Lamar University — Belize marine critters',
    url: 'https://www.lamar.edu/arts-sciences/biology/study-abroad-belize/marine-critters/marine-critters-2/cushion-star.html',
    supports: 'The cushion sea star lives on sand and seagrass in Belize; five short, thick arms.',
    accessed: '2026-10-07',
  },
  {
    id: 'knowable-sea-cucumber',
    title: 'The weird and wondrous world of sea cucumbers',
    publisher: 'Knowable Magazine',
    url: 'https://knowablemagazine.org/content/article/living-world/2025/weird-wondrous-sea-cucumbers',
    supports: 'Sea cucumbers eat sediment and leave cleaned sand behind as they move along the seafloor.',
    accessed: '2026-10-07',
  },
  {
    id: 'britannica-hermit-crab',
    title: 'Hermit crab',
    publisher: 'Encyclopaedia Britannica',
    url: 'https://www.britannica.com/EBchecked/topic/263281/hermit-crab',
    supports: 'Hermit crabs live in empty snail shells and change to larger shells as they grow.',
    accessed: '2026-10-07',
  },
  {
    id: 'mote-sea-fan',
    title: 'Venus sea fan',
    publisher: 'Mote Marine Laboratory',
    url: 'https://mote.org/animal-encyclopedia/venus-sea-fan/',
    supports: 'Sea fans are soft corals whose polyps catch small food from the water.',
    accessed: '2026-10-07',
  },
  {
    id: 'noaa-barrel-sponge',
    title: 'Barrel sponge',
    publisher: 'NOAA Office of National Marine Sanctuaries',
    url: 'https://sanctuaries.noaa.gov/vr/flower-garden-banks/barrel-sponge/',
    supports: 'Sponges are animals that pump water through their bodies to filter food.',
    accessed: '2026-10-07',
  },
  {
    id: 'naturalis-brain-coral',
    title: 'Diploria labyrinthiformis (grooved brain coral)',
    publisher: 'Naturalis — Caribbean diving guide',
    url: 'https://caribbean-diving.linnaeus.naturalis.nl/linnaeus_ng/app/views/species/taxon.php?id=6735',
    supports: 'Grooved brain coral is a Caribbean reef-building coral whose grooves look like a brain.',
    accessed: '2026-10-07',
  },
];

export const sourceById = new Map(sources.map((s) => [s.id, s]));
